/** Node.js build plugin. Produces a Hono HTTP server with SSE/webhook/sync modes. */
import type { BuildContext, BuildPlugin } from './types.ts';

export class NodePlugin implements BuildPlugin {
	name = 'node';
	// Node has no platform-provided bundler — esbuild is our final-output
	// step here, producing a single self-contained `dist/server.mjs`.
	bundle = 'esbuild' as const;

	generateEntryPoint(ctx: BuildContext): string {
		const { agents, roles } = ctx;
		const rolesJson = JSON.stringify(roles);
		// Inline the user-defined models map as a JSON literal. Definitions are
		// JSON-serializable by construction (see `defineOpenAICompletionsModel`),
		// so this round-trips losslessly. An empty object is the no-models
		// default.
		const userModelsJson = JSON.stringify(ctx.options.models ?? {});

		const webhookAgents = agents.filter((a) => a.triggers.webhook);

		// Generate import statements for all agent handlers. We register every
		// agent — including trigger-less ones — in the handler map so that the
		// CLI's `flue run` can invoke them in local mode. The `webhookAgents`
		// list below gates which are reachable over public HTTP when deployed.
		const agentImports = agents
			.map((a, index) => {
				const varName = agentVarName(a.name, index);
				const filePath = a.filePath.replace(/\\/g, '/');
				return `import ${varName} from '${filePath}';`;
			})
			.join('\n');

		// Build the handler map — includes ALL agents, not just webhook ones.
		const handlerMapEntries = agents
			.map((a, index) => `  ${JSON.stringify(a.name)}: ${agentVarName(a.name, index)},`)
			.join('\n');

		// Webhook agent names. `createFlueApp` accepts any iterable of names
		// and snapshots it once internally, so a plain array literal is fine.
		const webhookNames = JSON.stringify(webhookAgents.map((a) => a.name));

		// Manifest for /agents endpoint
		const manifest = JSON.stringify(
			{
				agents: agents.map((a) => ({
					name: a.name,
					triggers: a.triggers,
				})),
			},
			null,
			2,
		);

		// All HTTP routing, SSE/webhook/sync mode handling, agent dispatch,
		// and error rendering live in the SDK's runtime modules. The
		// generated entry's job is now narrow: import handlers, build the
		// runtime config, instantiate sandboxes, start the listener.
		return `
// Auto-generated by @flue/sdk build (node)
import { serve } from '@hono/node-server';
import { Bash, InMemoryFs, MountableFs, ReadWriteFs } from 'just-bash';
import {
  createFlueContext,
  InMemorySessionStore,
  bashFactoryToSessionEnv,
  resolveModel,
  createFlueApp,
} from '@flue/sdk/internal';

${agentImports}

// ─── Config ─────────────────────────────────────────────────────────────────

const skills = {};
const roles = ${rolesJson};
const systemPrompt = '';

// User-defined model providers from flue.config.ts. Inlined at build time;
// the resolver below binds it as the third arg to \`resolveModel\` so the
// agent runtime stays oblivious to where the map came from.
const userModels = ${userModelsJson};
const resolveModelWithUserModels = (model, providers) => resolveModel(model, providers, userModels);

const handlers = {
${handlerMapEntries}
};

// Webhook-accessible agent names.
const webhookAgentNames = ${webhookNames};

// When the CLI starts this server via \`flue run\`, it sets FLUE_MODE=local.
// In local mode the HTTP route accepts any registered agent (including
// trigger-less CI-only agents). In any other mode the route is restricted to
// agents with \`webhook: true\`, preventing accidental public exposure of
// agents that the user only intended to invoke from their CI pipeline.
const isLocalMode = process.env.FLUE_MODE === 'local';

const manifest = ${manifest};

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 * Uses InMemoryFs (no real filesystem access) with sensible defaults:
 * cwd = /home/user, /tmp exists, /bin and /usr/bin exist.
 */
async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

/**
 * Create a local sandbox backed by the host filesystem.
 * Mounts process.cwd() at /workspace via ReadWriteFs + MountableFs.
 */
async function createLocalEnv() {
  const rwfs = new ReadWriteFs({ root: process.cwd() });
  const fs = new MountableFs({ base: new InMemoryFs() });
  fs.mount('/workspace', rwfs);
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    cwd: '/workspace',
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

// Default persistence store for Node — in-memory, process lifetime.
const defaultStore = new InMemorySessionStore();

function createContextForRequest(id, payload, req) {
  return createFlueContext({
    id,
    payload,
    env: process.env,
    req,
    agentConfig: {
      systemPrompt, skills, roles, model: undefined, resolveModel: resolveModelWithUserModels,
    },
    createDefaultEnv,
    createLocalEnv,
    defaultStore,
  });
}

// ─── Server ─────────────────────────────────────────────────────────────────

// All HTTP routing and per-agent dispatch lives in the SDK's runtime module.
// Webhook + SSE foreground execution use the default in-process runners
// (just-call-the-handler) — no DO keepalive / fiber wrapping is needed on
// Node.
const app = createFlueApp({
  manifest,
  handlers,
  webhookAgents: webhookAgentNames,
  allowNonWebhook: isLocalMode,
  createContext: createContextForRequest,
});

// ─── Start ──────────────────────────────────────────────────────────────────

const port = parseInt(process.env.PORT || '3000', 10);

const server = serve({
  fetch: app.fetch,
  port,
  // SSE requests can outlive Node's default 300s request timeout.
  serverOptions: { requestTimeout: 0 },
});
console.log('[flue] Server listening on http://localhost:' + port);
if (isLocalMode) {
  console.log('[flue] Mode: local (all agents invokable, including trigger-less)');
  console.log('[flue] Available agents: ' + ${JSON.stringify(agents.map((a) => a.name).join(', '))});
} else {
  console.log('[flue] Available agents: ' + ${JSON.stringify(webhookAgents.map((a) => a.name).join(', '))});
}

process.on('SIGINT', () => { server.close(); process.exit(0); });
process.on('SIGTERM', () => { server.close(); process.exit(0); });
`;
	}

	esbuildOptions(_ctx: BuildContext): Record<string, any> {
		return {
			platform: 'node',
			target: 'node22',
			// just-bash's archive code wraps these native addons in dynamic imports
			// inside try/catch and declares them as optionalDependencies. Externalize
			// so esbuild doesn't try to resolve them at bundle time — the failure
			// path is handled by just-bash at runtime with a clear error message.
			external: ['node-liblzma', '@mongodb-js/zstd'],
		};
	}
}

function agentVarName(name: string, index: number): string {
	const readableName = name.replace(/[^a-zA-Z0-9]/g, '_').replace(/^_+|_+$/g, '') || 'agent';
	return `handler_${readableName}_${index}`;
}
